version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /.*
  script: demo_user.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
